version: '3.9'

services:
  db:
    image:  mysql:8.3.0
    command: mysqld --default_authentication_plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: appdev
      MYSQL_ROOT_HOST: '%'      
    ports:
      - 3308:3306    
    networks:
      - erudio-network   

  docker-from-zero-to-mastery-java:
    image: adrileyf/docker-from-zero-to-mastery-java
    restart: always
    working_dir: /app
    environment:
      TZ: America/Sao_Paulo     
    ports:
      - 8080:8080
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - erudio-network
networks:
  erudio-network:
    driver: bridge