version: '3.9'

services:
  db:
    image: mysql:8.3.0
    command: mysqld --default_authentication_plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: devapp
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3306
    ports:
      - 3307:3306
    expose:
      - 3306
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
